chore(package): upgrade jest
jest ^22 has issue, when running it breaks with:
```
 SecurityError: localStorage is not available for opaque origins

             at Window.get localStorage [as localStorage]
             (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
                       at Array.forEach (<anonymous>)
```

jest ^23 no longer has this issue

more https://github.com/jsdom/jsdom/issues/2304